import { DemoRole } from "../../common/demo-data";

export const Permission = {
  dashboardStaffRead: "dashboard.staff.read",
  dashboardResidentRead: "dashboard.resident.read",
  dashboardBusinessRead: "dashboard.business.read",
  notificationsRead: "notifications.read",
  tasksRead: "tasks.read",
  documentsRead: "documents.read",
  searchRead: "search.read",
  contactCreate: "contact.create",

  benefitsView: "benefits.view",
  benefitsCreate: "benefits.create",
  benefitsReview: "benefits.review",

  procurementView: "procurement.view",
  procurementCreate: "procurement.create",
  procurementReview: "procurement.review",
  procurementSubmitBid: "procurement.submit_bid",

  grantsView: "grants.view",
  grantsCreate: "grants.create",
  grantsReview: "grants.review",

  businessLicensingView: "business_licensing.view",
  businessLicensingCreate: "business_licensing.create",
  businessLicensingReview: "business_licensing.review",

  economicDevelopmentView: "economic_development.view",
  economicDevelopmentManage: "economic_development.manage",

  recordsRequestsView: "records_requests.view",
  recordsRequestsCreate: "records_requests.create",
  recordsRequestsReview: "records_requests.review",

  legislativeView: "legislative.view",
  legislativeManage: "legislative.manage",

  courtsView: "courts.view",
  courtsManage: "courts.manage",

  publicSafetyView: "public_safety.view",
  publicSafetyFileReport: "public_safety.file_report",
  publicSafetyReview: "public_safety.review",

  executiveView: "executive.view",
  documentsManage: "documents.manage",
  workflowsManage: "workflows.manage",

  codeEnforcementView: "code_enforcement.view",
  codeEnforcementManage: "code_enforcement.manage",
  inspectionsView: "inspections.view",
  inspectionsManage: "inspections.manage",
  utilitiesView: "utilities.view",
  utilitiesManage: "utilities.manage",
  assetsView: "assets.view",
  communicationsView: "communications.view",
  communicationsManage: "communications.manage",
  emergencyView: "emergency.view",
  capitalPlanningView: "capital_planning.view",
  financeView: "finance.view",
  clerkView: "clerk.view",
  integrationsManage: "integrations.manage",
  complianceView: "compliance.view",

  mapView: "map.view",
  contractsView: "contracts.view",
  vendorPerformanceView: "vendor_performance.view",
  fundingView: "funding.view",
  constituentsView: "constituents.view",
  workforceView: "workforce.view",
  strategyView: "strategy.view",
  onboardingManage: "onboarding.manage",
  reportsView: "reports.view",
  paymentsView: "payments.view",
  regionalView: "regional.view",
  marketplaceView: "marketplace.view",

  permitsView: "permits.view",
  permitsCreate: "permits.create",
  permitsReview: "permits.review",
  permitsAssign: "permits.assign",
  inspectionsSchedule: "inspections.schedule",

  zoningView: "zoning.view",
  zoningCreate: "zoning.create",
  zoningReview: "zoning.review",

  infrastructureView: "infrastructure.view",
  infrastructureManage: "infrastructure.manage",

  serviceRequestsView: "service_requests.view",
  serviceRequestsCreate: "service_requests.create",
  serviceRequestsAssign: "service_requests.assign",
  serviceRequestsResolve: "service_requests.resolve"
} as const;

export type PermissionKey = (typeof Permission)[keyof typeof Permission];

const staffCore = [
  Permission.dashboardStaffRead,
  Permission.notificationsRead,
  Permission.tasksRead,
  Permission.documentsRead,
  Permission.searchRead,
  Permission.permitsView,
  Permission.permitsReview,
  Permission.permitsAssign,
  Permission.inspectionsSchedule,
  Permission.zoningView,
  Permission.zoningReview,
  Permission.infrastructureView,
  Permission.infrastructureManage,
  Permission.serviceRequestsView,
  Permission.serviceRequestsAssign,
  Permission.serviceRequestsResolve,

  Permission.benefitsView,
  Permission.benefitsReview,
  Permission.procurementView,
  Permission.procurementCreate,
  Permission.procurementReview,
  Permission.grantsView,
  Permission.grantsReview,
  Permission.businessLicensingView,
  Permission.businessLicensingReview,
  Permission.economicDevelopmentView,
  Permission.economicDevelopmentManage,
  Permission.recordsRequestsView,
  Permission.recordsRequestsReview,
  Permission.legislativeView,
  Permission.legislativeManage,
  Permission.courtsView,
  Permission.courtsManage,
  Permission.publicSafetyView,
  Permission.publicSafetyReview,
  Permission.executiveView,
  Permission.documentsManage,
  Permission.workflowsManage,
  Permission.codeEnforcementView,
  Permission.codeEnforcementManage,
  Permission.inspectionsView,
  Permission.inspectionsManage,
  Permission.utilitiesView,
  Permission.utilitiesManage,
  Permission.assetsView,
  Permission.communicationsView,
  Permission.communicationsManage,
  Permission.emergencyView,
  Permission.capitalPlanningView,
  Permission.financeView,
  Permission.clerkView,
  Permission.integrationsManage,
  Permission.complianceView,
  Permission.mapView,
  Permission.contractsView,
  Permission.vendorPerformanceView,
  Permission.fundingView,
  Permission.constituentsView,
  Permission.workforceView,
  Permission.strategyView,
  Permission.onboardingManage,
  Permission.reportsView,
  Permission.paymentsView,
  Permission.regionalView,
  Permission.marketplaceView,

];

export const rolePermissions: Record<DemoRole, PermissionKey[]> = {
  municipality_admin: Object.values(Permission),
  staff: staffCore,
  resident: [
    Permission.dashboardResidentRead,
    Permission.notificationsRead,
    Permission.documentsRead,
    Permission.searchRead,
    Permission.permitsCreate,
    Permission.permitsView,
    Permission.serviceRequestsCreate,
    Permission.serviceRequestsView,
    Permission.benefitsCreate,
    Permission.benefitsView,
    Permission.grantsCreate,
    Permission.grantsView,
    Permission.recordsRequestsCreate,
    Permission.recordsRequestsView,
    Permission.communicationsView,
    Permission.marketplaceView,
    Permission.paymentsView
  ],
  vendor: [
    Permission.dashboardBusinessRead,
    Permission.notificationsRead,
    Permission.documentsRead,
    Permission.searchRead,
    Permission.permitsView,
    Permission.serviceRequestsView,
    Permission.procurementSubmitBid,
    Permission.procurementView,
    Permission.businessLicensingCreate,
    Permission.businessLicensingView,
    Permission.grantsCreate,
    Permission.grantsView,
    Permission.recordsRequestsCreate,
    Permission.recordsRequestsView,
    Permission.communicationsView,
    Permission.economicDevelopmentView,
    Permission.procurementSubmitBid,
    Permission.businessLicensingCreate,
    Permission.vendorPerformanceView,
    Permission.marketplaceView,
    Permission.paymentsView
  ],
  platform_admin: Object.values(Permission)
};
